Medidas de posicion

In [2]:

import numpy as np
import pandas as pd
# Cuantiles

lanzamientos_dados = np.random.randint(1,5,50)
lanzamientos_dados



array([1, 4, 4, 1, 3, 2, 3, 4, 2, 4, 3, 2, 3, 2, 2, 2, 3, 2, 4, 2, 2, 3,
       1, 1, 1, 1, 1, 4, 3, 4, 4, 1, 3, 1, 2, 3, 1, 4, 3, 2, 4, 3, 2, 4,
       3, 1, 1, 3, 2, 4])

In [18]:
len(lanzamientos_dados)

50

In [3]:
lanzamientos_dados = np.sort(lanzamientos_dados)
lanzamientos_dados

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4])

In [4]:

# 1er paso serializar el arreglo, conviertiendolo a un objeti de panda tipo Series
ld_con_indice = pd.Series(lanzamientos_dados)
ld_con_indice

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    4
39    4
40    4
41    4
42    4
43    4
44    4
45    4
46    4
47    4
48    4
49    4
dtype: int32

In [4]:
# frecuencia absoluta

ld_frecuencia_absoluta = pd.crosstab(index=ld_con_indice, columns ="cantidad")
ld_frecuencia_absoluta

col_0  cantidad
row_0          
1            14
2            12
3             9
4            15

In [5]:
# Frecuencia relativa

ld_frecuencia_relativa = ld_frecuencia_absoluta / ld_frecuencia_absoluta.sum()*100
ld_frecuencia_relativa


col_0  cantidad
row_0          
1          28.0
2          24.0
3          18.0
4          30.0

In [6]:
# frecuencia absoluta acumulada

ld_frecuencia_absoluta_acum = ld_frecuencia_absoluta.cumsum()
ld_frecuencia_absoluta_acum

col_0  cantidad
row_0          
1            14
2            26
3            35
4            50

In [8]:
# frecuencia relativa acumulada

#ld_frecuencia_relativa_acum = ld_frecuencia_absoluta_acum/ld_frecuencia_absoluta.sum()*100
ld_frecuencia_relativa_acum = ld_frecuencia_relativa.cumsum()
ld_frecuencia_relativa_acum

col_0  cantidad
row_0          
1          28.0
2          52.0
3          70.0
4         100.0

In [9]:
reporte_frecuencia_ld = pd.DataFrame({
    'frecuencia_absoluta' : ld_frecuencia_absoluta.to_numpy().flatten(),
    'frecuencia_relativa' : ld_frecuencia_relativa.to_numpy().flatten(),
    'frecuencia_absoluta_acum' : ld_frecuencia_absoluta_acum.to_numpy().flatten(),
    'frecuencia_relativa_acum' : ld_frecuencia_relativa_acum.to_numpy().flatten(),
},
index=[1,2,3,4])

reporte_frecuencia_ld

frecuencia_absoluta  frecuencia_relativa  frecuencia_absoluta_acum  \
1                   14                 28.0                        14   
2                   12                 24.0                        26   
3                    9                 18.0                        35   
4                   15                 30.0                        50   

   frecuencia_relativa_acum  
1                      28.0  
2                      52.0  
3                      70.0  
4                     100.0

In [53]:
reporte_frecuencia_ld['frecuencia_relativa_acum']

1     30.0
2     50.0
3     64.0
4    100.0
Name: frecuencia_relativa_acum, dtype: float64

In [10]:
# .quantile(arreglo, quantile_en_decimal)
np.quantile(lanzamientos_dados, 0.10)

1.0

In [12]:
np.quantile(lanzamientos_dados, 0.75)

4.0

In [5]:
# cuartil
# le especificams el en arreglo que quartiles requerimos
quartiles = np.percentile(ld_con_indice, [25,50,75])
quartiles

array([2. , 2.5, 3. ])

In [ ]:
# Ejemplo cuantil 0.