# Numpy
Numeric - Python  => Libreria para manipulacion de grandes conjuntos de datos y matrices, siempre y cuando sean datos homogeneos

In [2]:
import numpy as np
#as np   para que pueda ser llamado como np..

#from numpy import * 

#de esta forma tambien se importa y no necesita prefijo para llamar alguna funcion de la libreria
# se invica la funcion con solo el nombre propio, lo malo es que puede confundirse con otros nombres de funcion

In [2]:
L1 = [1,2,3,4]   #Lista

In [7]:
x1 = np.array(L1)   #.array(lista)   convierte una lista o tupla a array
x1

array([1, 2, 3, 4])

In [5]:
x2 = np.array(L1, dtype='float')   #.array(lista, dtype="formato al cual se convertira cada elemento del arreglo")
x2

array([1., 2., 3., 4.])

In [13]:
# Tipos de datos en array

# // Si no se especifica en el int_numero_ float_numero se tomara por defecto el de 64

# bool   # boleano
# int , intc, int8, int16, int32, int64   # enteros de diferentes tamaños
# uint, uint8, uint16, uint32, uint64   #entero sin signo 
# float, float16, float32, float64  # float
# complex, complex64, complex128   # numeros complejos

In [14]:
# .zeros(filas, columnas)   // crea una matriz de un tamañoi definido en ceros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# .ones(filas, columnas)   // crea una matriz de un tamañoi definido en unos
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# .range( valor inicial, valor final?, tipo de dato?  )  // permite crear un arreglo incremental de 1 fila, solo es requerido el primer valor
# los demas son opcionales
np.arange(3, 15, dtype="int8")   

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int8)

In [7]:
# .arange(valor inicial, valor final, intervalo)
np.arange(4,5,0.01)  # crea un arreglo en intervalos de 0.1  de 4 hasta 5

array([4.  , 4.01, 4.02, 4.03, 4.04, 4.05, 4.06, 4.07, 4.08, 4.09, 4.1 ,
       4.11, 4.12, 4.13, 4.14, 4.15, 4.16, 4.17, 4.18, 4.19, 4.2 , 4.21,
       4.22, 4.23, 4.24, 4.25, 4.26, 4.27, 4.28, 4.29, 4.3 , 4.31, 4.32,
       4.33, 4.34, 4.35, 4.36, 4.37, 4.38, 4.39, 4.4 , 4.41, 4.42, 4.43,
       4.44, 4.45, 4.46, 4.47, 4.48, 4.49, 4.5 , 4.51, 4.52, 4.53, 4.54,
       4.55, 4.56, 4.57, 4.58, 4.59, 4.6 , 4.61, 4.62, 4.63, 4.64, 4.65,
       4.66, 4.67, 4.68, 4.69, 4.7 , 4.71, 4.72, 4.73, 4.74, 4.75, 4.76,
       4.77, 4.78, 4.79, 4.8 , 4.81, 4.82, 4.83, 4.84, 4.85, 4.86, 4.87,
       4.88, 4.89, 4.9 , 4.91, 4.92, 4.93, 4.94, 4.95, 4.96, 4.97, 4.98,
       4.99])

In [32]:
# .linspace(valor inicial, valor final, cantidad numeros a generar)   # genera dentro de un rango n cantidad de numeros
np.linspace(1,70,15)

array([ 1.        ,  5.92857143, 10.85714286, 15.78571429, 20.71428571,
       25.64285714, 30.57142857, 35.5       , 40.42857143, 45.35714286,
       50.28571429, 55.21428571, 60.14285714, 65.07142857, 70.        ])

In [9]:
# .eye(filas, columnas?)  # crea una matriz con unos en diagonal, las columnas son opcionales 
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
m = np.arange(24)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
# .reshape(filas, columnas)  # permite reacomodar a una nuevas posiciones la matriz, siempre y cuando sean equivalentes
m.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
h = np.array([
    [1,2,3],
    [4,5,6]
])
h


array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
# .ravel(arreglo)   // permite hacer de un arreglo multidimencional a unidimensional de una sola fila
np.ravel(h)

array([1, 2, 3, 4, 5, 6])

In [56]:
# arreglo.flatten()    //funcion que hace lo mismo que ravel, pero esta hace una copia y no edita el original como ravel
h.flatten()   

array([1, 2, 3, 4, 5, 6])

In [57]:
# .transpose(arreglo)   // organiza el arreglo de forma vertical
np.transpose(h) 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
arreglo1 = np.linspace(1,20,15)  # creamos arreglo entre 1 a 20 de 15 posiciones
arreglo1

array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
        7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
       14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ])

In [66]:
# .resize(arreglo, (filas, columnas)) # permite darle un nuevo orden a un arreglo, de faltar elementos repite y de sobrar deja hasta donde alcance
np.resize(arreglo1, (10,3))

array([[ 1.        ,  2.35714286,  3.71428571],
       [ 5.07142857,  6.42857143,  7.78571429],
       [ 9.14285714, 10.5       , 11.85714286],
       [13.21428571, 14.57142857, 15.92857143],
       [17.28571429, 18.64285714, 20.        ],
       [ 1.        ,  2.35714286,  3.71428571],
       [ 5.07142857,  6.42857143,  7.78571429],
       [ 9.14285714, 10.5       , 11.85714286],
       [13.21428571, 14.57142857, 15.92857143],
       [17.28571429, 18.64285714, 20.        ]])

# Test

- 1 Array con valores entre 5 y 120
- 2 Matriz 4*4 con valores desde 0 - 15
- 3 Identidad 7*7    //Una identidad tiene mismas filas y columnas
- 4 Array de 20 elementos y trasnformarlos en una matriz 5*4
- 5 Array de 20 numeros con valores entre 0 y 5, espaciados uniformente

In [69]:
#1 Array con valores entre 5 y 120
n1 = np.arange(5,121)
n1

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [73]:
#2 Matriz 4*4 con valores desde 0 - 15
n2 = np.resize(np.arange(0,15),(4,4))
n2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0]])

In [75]:
#3 Identidad 7*7
n3 = np.eye(7)
n3

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [77]:
#4 Array de 20 elementos y trasnformarlos en una matriz 5*4
arreglo_base = np.linspace(1,20,20)
arreglo_base

np.resize(arreglo_base, (5,4))

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [78]:
#5 Array de 20 numeros con valores entre 0 y 5, espaciados uniformente

n3 = np.linspace(0,5,20)
n3

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Propiedades de los array

In [18]:
x = np.arange(12)+1   # crea un arreglo de 12 posiciones y le +1 a cada posicion
x = x.reshape((3,4)) #Converite el arreglo a 3 filas y 12 columnas
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# .ndim retorna el numero de dimenciones del arreglo
x.ndim

2

In [20]:
# .shape   retorna cuantas filas y columnas tiene
x.shape

(3, 4)

In [21]:
# x.size   retorna el numero de elementos que tiene la matriz
x.size

12

In [22]:
# .dtype   retorna el tipo de dato que contiene la matriz
x.dtype

dtype('int32')

In [23]:
# .xitemsize   retorna la cantidad en bytes que cada posicion representa en la matriz
x.itemsize

4

In [ ]:
# .data    retorna el buffer enb la posicion de memoria ram, donde se almacena esta matriz
x.data

In [28]:
x[2]   # accediendo a la fila

array([ 9, 10, 11, 12])

In [27]:
x[2,2]  # accediendo a la fila y columna

11

In [29]:
x.shape = (4,3)   #cambiando la forma de la matriz a 4 filas y 3 columnas
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
x[1:3, 0:2]   # Retorna las posoiciones de la fila 1 a la 3 y de la columna 0 a la 2

array([[4, 5],
       [7, 8]])

In [31]:
y = np.arange(15)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
y[3:12]   # accede a las posiciones 3 a la 12

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
y[3:12:3]   # accede a las posiciones 3 a la 12  en intervalos de 3

array([3, 6, 9])

In [41]:
z = np.arange(10,6,-1) #(valor maximo, valor minimo, salto o intervalo)
z

array([10,  9,  8,  7])

In [42]:
p = np.arange(60)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [45]:
p[p>50]   # En ves de recibir una posicion recibe un condicional de filtrado, las que cumpla retornara

array([51, 52, 53, 54, 55, 56, 57, 58, 59])

In [50]:
p[12:24] = 2    # selecciona un rango de la matriz, y a todas sus posiciones le asgina un valor
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [51]:
p[20:23] = [99,100,101]  # reasinando masivamente a las posiciones establecidas, con la misma cantidad de valores en el arreglo
p

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,   2,
         2,   2,   2,   2,   2,   2,   2,  99, 100, 101,   2,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59])

# Copias y vistas de Arrays

In [52]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
y = x
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
x    # aunque se asigno en una variable el contenido de Y, tambien se vio alterado y modificado x
# cuando se asigna una variable a otra, solo se referencia en otra variable por lo cual es como si se modificara la primer variable

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
# arreglo.copy()  realiza una copia del arreglo y lo a la nueva variable   
z = y.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
z[1:2] = 0
z 

array([[0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0]])

In [59]:
y  # no se modifica Y ya que se realizo una copia

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
y is z

False

In [61]:
x is y

True

In [62]:
k = x.view()  # genera una vista al arreglo inicial, permitiendo hacer modificaciones sobre la nueva variable sin alterar la anterior
k

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
k.resize(5,2)
k

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [67]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
s = x[1:2, 2:4]  # tomo los datos de x[fila 1 a la 2, columna 2 a la 4]
s   # cuando se hace un filtro de esta forma se hace una vista como si se usara .view()

array([[5, 5]])

In [75]:
s[:] = 5   #[:]  sifnifica seleccionar todos los elemenos = 5
s

array([[5, 5]])

# Funcion universales (ufunc)

- Unarias:  Funciones que se aplican elemento a elemento
sqrt, sin, cos, **2

- Binarias: Funciones que reciben 2 array y retornan uno o mas arrays
maximum, minimun

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x+3   # se suma el valor a cada una de las posiciones

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
alpha = np.linspace(0,2*np.pi,4)    # .linspace (valor_inicial, valor_final, cantidad_valores)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [8]:
np.sin(alpha)  #retorna para cada posicion el seno

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [10]:
np.exp(x)  # eleva cada elemento a la potencia de cada posicion

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [12]:
np.exp2(x)   # eleva al cuadrado ´todas las posiciones

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [13]:
np.power(5, x)   # .power(potencia, arreglo_base)

array([      1,       5,      25,     125,     625,    3125,   15625,
         78125,  390625, 1953125], dtype=int32)

In [14]:
np.sum(x)  #suma todos los valores del arreglo

45

In [15]:
np.nansum(x)   # suma todos los valores del arreglo descartando valores nan

45

In [16]:
np.prod(x)   # multilicacion de todos los elementos

0

In [17]:
np.mean(x)  # obtiene la media del arreglo

4.5

In [18]:
np.median(x)  # obtiene la mediana del arreglo  (organiza el arreglo y obtiene la mitad)

4.5

In [19]:
np.min(x)  # obtiene el valor menor

0

In [20]:
np.max(x)  # obtiene el valor mayor

9

# Desviacion tipica
La desviación típica se define como la raíz cuadrada de la varianza de la variable. Sirve principalmente para conocer la desviación que presentan los datos en su distribución respecto a la media aritmética de dicha distribución. Es decir, nos muestra una visión más acorde con la realidad en el momento de tomar las decisiones.

https://okdiario.com/curiosidades/desviacion-tipica-1133576

In [21]:
np.std(x)   # Obtiene la desviacion tipica

2.8722813232690143

# Varianza
La varianza es una medida de dispersión que representa la variabilidad de una serie de datos respecto a su media. Formalmente se calcula como la suma de las residuos al cuadrado divididos entre el total de observaciones.

https://economipedia.com/definiciones/varianza.html

In [26]:
h = np.var(x)   # Obtiene la varianza
h

8.25

In [27]:
np.argmin(x)  # posicion en la que se encuentra el valor minimo

0

In [28]:
np.argmax(x)  # posicion en la que se encuentra el valor maximo

9

In [30]:
np.percentile(x, q=0.5)   # calcula los percentiles  (arreglo, numero de percentil a obtener)

0.045

In [32]:
i = np.array([True, True, False, False])
i

array([ True,  True, False, False])

In [33]:
np.any(i)   # Devuelve true si alguno de los valores es bolean true

True

In [34]:
np.all(i)  # Devuelve true si cada uno de los elementros es true

False

In [36]:
z = np.random.random((3,5))  # .random.random((filas, columnas))   # llena una matriz de valores aleatorios 
z

array([[0.65703516, 0.96386252, 0.30579659, 0.87551292, 0.11145556],
       [0.6526449 , 0.16924299, 0.94105228, 0.23616791, 0.41510219],
       [0.40130006, 0.68397612, 0.75286741, 0.89416253, 0.20899634]])

In [37]:
z.sum() # Realiza la suma de todos los valores de la matriz

8.269175502673189

In [38]:
z.sum(axis=0)  # axis=0  realiza la suma de todas las columnas y devuelve un vector con la sumatoria

array([1.71098012, 1.81708163, 1.99971628, 2.00584336, 0.7355541 ])

In [39]:
z.sum(axis=1)  # axis=1  realiza la suma de todas las filas y devuelve un vector con la sumatoria

array([2.91366276, 2.41421027, 2.94130247])

In [40]:
z.sum(axis=2)    # axis=2  suma la profundidad de la otra dimension

AxisError: axis 2 is out of bounds for array of dimension 2

In [44]:
np.random.seed(2020)   # permite generar una base para la generacion de numeros aleatorios, de forma que siempre sean los mismo
j = np.random.random((5,6))
j

array([[0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873,
        0.21695427],
       [0.27647714, 0.34331559, 0.86215894, 0.15669967, 0.14088724,
        0.75708028],
       [0.73632492, 0.35566309, 0.34109302, 0.66680305, 0.21710064,
        0.56142698],
       [0.12417878, 0.31973648, 0.95321387, 0.13735679, 0.5694131 ,
        0.97566548],
       [0.50336706, 0.66766421, 0.0341915 , 0.45611937, 0.15585136,
        0.47604897]])

In [45]:
j.sum()

13.982960538301068

# Matricez Np Algebra lineal


In [47]:
matriz1 = [
    [1,2,3],
    [4,5,6]
]

matriz1

[[1, 2, 3], [4, 5, 6]]

In [49]:
matriz1[0][0]  # accediando a la fila 1 columna 1

1

In [50]:
matriz1[0]   # accediendo a la primer fila

[1, 2, 3]

In [52]:
matriz2= np.array(matriz1, dtype=float)
matriz2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [53]:
matriz1+matriz2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [62]:
matriz1 = np.resize(matriz1,(3,3))
matriz2 = np.resize(matriz2,(3,3))
print(matriz1)
print(matriz2)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]]


In [61]:
matriz1.dot(matriz2)   #.dot(matriz) producto matricial

array([[12., 18., 24.],
       [30., 45., 60.],
       [12., 18., 24.]])

In [63]:
matriz1.transpose()   # .trasnpose() trasnforma las filas hacia las columnas

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [64]:
matriz1.trace()   # .trace()  suma de los elementos en la diagonal

9

In [65]:
np.linalg.matrix_rank(matriz1)

2